site_name: WSO2 Enterprise Integrator Documentation

nav:
 - Deployment:
   - Clustering: 'server_conn.md'
   - Data Stores: ''
   - Multitenancy: ''
   - Performance Tuning: ''
   - Configuration Catalog:
     - Server Connections: 'server_conn.md'
     - Datasources: 'datasources.md'
     - User Management: 'user_management.md'
     - Clustering: 'clustering.md'
     - Security: 'security.md'
     - Multitenancy: 'multitenancy.md' 
     - Data Publishing: 'data_publishing'
     - Management Console: 'management_console.md'
     - Transports: 'transports.md'
     - Mediation: 'mediation.md'

theme:
  name: 'material'
  palette: 
    primary: 'blue grey'
    accent: 'deep orange'
  font:
    text: 'Nunito Sans'
    code: 'Courier New'
  logo: 'images/WSO2_Software_Logo.png'
  language: 'en'
  feature:
    tabs: true 